seegno/uphold-sdk-php

lib/Bitreserve/BitreserveClient.php

User agent now adds automaticly the bitreserve client version.

Improve user agent

---

lib/Bitreserve/Model/Card.php
lib/Bitreserve/Model/User.php

Replace array reduce by array map

---

README.md
composer.json
lib/Bitreserve/BitreserveClient.php
lib/Bitreserve/Command/CreateTokenCommand.php
lib/Bitreserve/console.php
test/Bitreserve/Tests/BitreserveClientTest.php

Add command to create new personal access token

---

lib/Bitreserve/BitreserveClient.php
test/Bitreserve/Tests/BitreserveClientTest.php

OAuth2 tokens endpoint was updated on Bitreserve API.

Update OAuth2 tokens endpoint

---

lib/Bitreserve/Model/Card.php
lib/Bitreserve/Model/CardInterface.php
test/Bitreserve/Tests/Model/CardTest.php

* Remove position property.
* Add settings property.
* Update card model tests.

Update card model

---

README.md
examples/Card.php
examples/Ticker.php
examples/Transaction.php
examples/User.php
lib/Bitreserve/Model/BaseModel.php
test/Bitreserve/Tests/BitreserveClientTest.php
test/Bitreserve/Tests/Functional/BitreserveClientTest.php
test/Bitreserve/Tests/HttpClient/Handler/ErrorHandlerTest.php
test/Bitreserve/Tests/HttpClient/Message/ResponseMediatorTest.php
test/Bitreserve/Tests/Model/TestCase.php
test/Bitreserve/Tests/Model/UserTest.php

This adds some small code improvements.

Add code improvements

---

examples/Reserve.php
lib/Bitreserve/Model/Reserve.php
test/Bitreserve/Tests/Model/ReserveTest.php

This adds a new method in the Reserve model that returns the ledger endpoint data.
Closes #47.

Add reserve ledger endpoint

---

lib/Bitreserve/Model/Card.php
lib/Bitreserve/Model/CardInterface.php
test/Bitreserve/Tests/Model/CardTest.php

This removes an incorrect endpoint that was in the card model.

Remove incorrect endpoint from card model

---

examples/Reserve.php
examples/Transaction.php
lib/Bitreserve/HttpClient/Message/Response.php
lib/Bitreserve/Model/Card.php
lib/Bitreserve/Model/Reserve.php
lib/Bitreserve/Model/User.php
lib/Bitreserve/Paginator/Paginator.php
test/Bitreserve/Tests/BitreserveClientTest.php
test/Bitreserve/Tests/Functional/BitreserveClientTest.php
test/Bitreserve/Tests/HttpClient/Message/ResponseTest.php
test/Bitreserve/Tests/Model/CardTest.php
test/Bitreserve/Tests/Model/ReserveTest.php
test/Bitreserve/Tests/Model/UserTest.php
test/Bitreserve/Tests/Paginator/PaginatorTest.php

This adds support for api endpoints that have pagination.

Add pagination support

---

README.md

This adds the `Pagination` section to the README file.

Add paginator examples to README

---

lib/Bitreserve/Exception/BitreserveClientException.php
test/Bitreserve/Tests/Exception/BitreserveClientExceptionTest.php

* Fix return value of `getRequest` method
* Add bitreserve client exception tests

Improve bitreserve client exception

---

lib/Bitreserve/Model/Transaction.php
lib/Bitreserve/Model/TransactionInterface.php
test/Bitreserve/Tests/Model/TransactionTest.php

* Add missing `type` variable.
* Update docblocks.
* Update transaction tests.

Improve transaction model

---

lib/Bitreserve/Exception/BitreserveClientException.php

Add missing variables declaration.

Update bitreserve client exception class

---

test/Bitreserve/Tests/Functional/ReserveTest.php

This adds some functional tests on the reserve model.

Add reserve model functional test

---

test/Bitreserve/Tests/Unit/BitreserveClientTest.php
test/Bitreserve/Tests/Unit/Exception/BitreserveClientExceptionTest.php
test/Bitreserve/Tests/Unit/HttpClient/Handler/ErrorHandlerTest.php
test/Bitreserve/Tests/Unit/HttpClient/HttpClientTest.php
test/Bitreserve/Tests/Unit/HttpClient/Message/ResponseTest.php
test/Bitreserve/Tests/Unit/Model/CardTest.php
test/Bitreserve/Tests/Unit/Model/ContactTest.php
test/Bitreserve/Tests/Unit/Model/ReserveTest.php
test/Bitreserve/Tests/Unit/Model/TestCase.php
test/Bitreserve/Tests/Unit/Model/TickerTest.php
test/Bitreserve/Tests/Unit/Model/TokenTest.php
test/Bitreserve/Tests/Unit/Model/TransactionTest.php
test/Bitreserve/Tests/Unit/Model/UserTest.php
test/Bitreserve/Tests/Unit/Paginator/PaginatorTest.php

Move all unit tests to `Tests/Unit` folder.

Add unit tests folder

---

composer.json
test/Bitreserve/Tests/TestCase.php
test/Bitreserve/Tests/Unit/BitreserveClientTest.php
test/Bitreserve/Tests/Unit/TestCase.php

* Add a base test case;
* Add test case for unit tests;
* Add faker dependency to composer;
* Add faker to `BitreserveClientTest`.

Add test cases

---

README.md
examples/Ticker.php
lib/Bitreserve/BitreserveClient.php
lib/Bitreserve/Model/Rate.php
lib/Bitreserve/Model/RateInterface.php
test/Bitreserve/Tests/Functional/BitreserveClientTest.php
test/Bitreserve/Tests/Unit/BitreserveClientTest.php
test/Bitreserve/Tests/Unit/Model/RateTest.php

Rename ticker model to rate model

---

lib/Bitreserve/Model/User.php
lib/Bitreserve/Model/UserInterface.php
test/Bitreserve/Tests/Unit/Model/UserTest.php

Add getter for currencies to user model

---

lib/Bitreserve/Command/CreateTokenCommand.php

The endpoint `POST /me/tokens` was updated and the response variable that contains the access token has changed.

Update create token response handle

---

README.md
composer.json
lib/Bitreserve/BitreserveClient.php
lib/Bitreserve/console.php

This PR replaces `Bitreserve` by `Uphold` in README and `composer.json`.

Rename Bitreserve to Uphold

---

examples/Card.php
lib/Uphold/Model/User.php
lib/Uphold/Model/UserInterface.php
test/Uphold/Tests/Unit/Model/UserTest.php

This PR adds a new method in the `User` model to get a card by address.
Closes #102.

Add method to get a card by address

---

README.md

This PR updates the package version on README installation instructions.

Update package version on README

---

README.md

This PR updates the Uphold API documentation url.

Update API documentation url

---

lib/Uphold/console.php

This PR removes an unnecessary require on console.

Remove unnecessary require on console

---

test/Uphold/Tests/Unit/Model/CardTest.php
test/Uphold/Tests/Unit/Model/ContactTest.php
test/Uphold/Tests/Unit/Model/RateTest.php
test/Uphold/Tests/Unit/Model/TransactionTest.php
test/Uphold/Tests/Unit/Model/UserTest.php

This adds a missing unit tests on `toArray` method to all models.

Improve models unit tests

---

lib/Uphold/HttpClient/Message/Response.php
test/Uphold/Tests/Unit/HttpClient/Message/ResponseTest.php

This improves unit tests of Response class by adding some missing tests and improving the `getResponseMock` method.

Improve Response unit tests

---

lib/Uphold/Model/Card.php
test/Uphold/Tests/Unit/Model/CardTest.php

This PR adds missing unit tests to Card model.

Improve Card model unit tests

---

lib/Uphold/HttpClient/Message/MessageFactory.php
test/Uphold/Tests/Unit/HttpClient/Message/MessageFactoryTest.php

This PR adds missing unit tests to the `MessageFactory` class.

Improve MessageFactory tests

---

test/Uphold/Tests/Unit/Factory/UpholdClientFactoryTest.php

This PR adds tests for `UpholdClientFactory`.

Add UpholdClientFactory tests

---

test/Uphold/Tests/Functional/UpholdClientTest.php
test/Uphold/Tests/Unit/UpholdClientTest.php

This adds and improves UpholdClient unit tests.

Improve UpholdClient unit tests

---

examples/Account.php
lib/Uphold/Model/Account.php
lib/Uphold/Model/AccountInterface.php
lib/Uphold/Model/User.php
lib/Uphold/Model/UserInterface.php
test/Uphold/Tests/Unit/Model/AccountTest.php
test/Uphold/Tests/Unit/Model/UserTest.php

This PR adds user accounts functionality such as:
- List accounts
- Get account details
Closes #133.

Add user accounts

---

lib/Uphold/Command/RevokeTokenCommand.php
lib/Uphold/console.php

This adds `RevokeTokenCommand` that allows revoking a user's token.
Closes #32

Add command to revoke a token

---

lib/Uphold/HttpClient/Handler/ErrorHandler.php
lib/Uphold/UpholdClient.php
test/Uphold/Tests/Unit/HttpClient/Handler/ErrorHandlerTest.php
test/Uphold/Tests/Unit/UpholdClientTest.php

This updates the OTP header to OTP-Token (previously X-Bitreserve-OTP).

Update OTP header

---

lib/Uphold/HttpClient/Message/Response.php
test/Uphold/Tests/Unit/HttpClient/Handler/ErrorHandlerTest.php
test/Uphold/Tests/Unit/HttpClient/Message/ResponseTest.php

This updates the following rate limit headers:
* X-RateLimit-Remaining to Rate-Limit-Remaining
* X-RateLimit-Reset to Rate-Limit-Reset
* X-RateLimit-Limit to Rate-Limit-Total

Update rate limit headers

---

README.md

This adds an example of `authorizeUser` to README.

Add authorizeUser example to README

---

README.md

This adds a tests section to README with instructions for running the
tests.
Closes #4

Add tests section to README
