lib/Bitreserve/BitreserveClient.php, lib/Bitreserve/HttpClient/HttpClient.php
When guzzle receives a `null` body, it automatically assumes a `Content-Length` of `0` and sends an empty body, as expected. However, since the `application/type` require is `json`, the body should be set to `{}` instead.
=> Fix empty string on request body

lib/Bitreserve/HttpClient/Message/ResponseMediator.php
Add generic messages to error and error description when response mediator handles the content of an request error.
=> Add generic messages to response mediator

lib/Bitreserve/Model/Card.php, lib/Bitreserve/Model/Transaction.php, lib/Bitreserve/Model/TransactionInterface.php, test/Bitreserve/Tests/Model/TransactionTest.php
The variable `cardId` was only used when creating a new transaction. The correct `cardId` used on transaction 'commit' or 'cancel' actions should be the one in the `origin` data, since only the transaction owner (origin) can do that operations.
=> Improve transaction model

README.md, examples/Reserve.php, lib/Bitreserve/BitreserveClient.php, lib/Bitreserve/Model/Reserve.php, lib/Bitreserve/Model/ReserveInterface.php, test/Bitreserve/Tests/BitreserveClientTest.php, test/Bitreserve/Tests/Model/ReserveTest.php
This adds the `/reserve/statistics` endpoint and also re-organize all `reserve` endpoints in a Reserve Model that can be accessed by BitreserveClient class.
=> Add reserve model

lib/Bitreserve/BitreserveClient.php, lib/Bitreserve/HttpClient/Handler/ErrorHandler.php, lib/Bitreserve/HttpClient/HttpClient.php, lib/Bitreserve/HttpClient/Message/MessageFactory.php, lib/Bitreserve/HttpClient/Message/Response.php, lib/Bitreserve/Model/Card.php, lib/Bitreserve/Model/Reserve.php, lib/Bitreserve/Model/Token.php, lib/Bitreserve/Model/Transaction.php, lib/Bitreserve/Model/User.php, test/Bitreserve/Tests/BitreserveClientTest.php, test/Bitreserve/Tests/Functional/BitreserveClientTest.php, test/Bitreserve/Tests/Functional/TestCase.php, test/Bitreserve/Tests/HttpClient/Handler/ErrorHandlerTest.php, test/Bitreserve/Tests/HttpClient/HttpClientTest.php, test/Bitreserve/Tests/HttpClient/Message/ResponseTest.php, test/Bitreserve/Tests/Model/CardTest.php, test/Bitreserve/Tests/Model/ContactTest.php, test/Bitreserve/Tests/Model/ReserveTest.php, test/Bitreserve/Tests/Model/TestCase.php, test/Bitreserve/Tests/Model/TickerTest.php, test/Bitreserve/Tests/Model/TokenTest.php, test/Bitreserve/Tests/Model/TransactionTest.php, test/Bitreserve/Tests/Model/UserTest.php
* Add a message response class to handle the response objects from the http requests.
* `BitreserveClient` http methods now returns full response.
* Models now handle directly the response objects.
* Update all tests.
=> Add response class for handle response objects

lib/Bitreserve/HttpClient/HttpClient.php
This removes variables that the `HttpClient` no longer uses.
=> Remove unused variables

lib/Bitreserve/BitreserveClient.php, lib/Bitreserve/Model/Transaction.php, lib/Bitreserve/Model/TransactionInterface.php, lib/Bitreserve/Model/User.php, lib/Bitreserve/Model/UserInterface.php, lib/Bitreserve/Paginator/Paginator.php, test/Bitreserve/Tests/Unit/BitreserveClientTest.php, test/Bitreserve/Tests/Unit/Model/TransactionTest.php, test/Bitreserve/Tests/Unit/Model/UserTest.php
This PR adds the following functionalities:
- Bitreserve Connect authentication method;
- Support for delete token operation;
- Improves pagination by adding a default limit of 50 items;
- Resend method for transactions.
Closes #85
=> Add OAuth support, improved pagination and transaction resend

.travis.yml
This PR updates the Code Climate secure token necessary due to the rename of the repository.
=> Update Code Climate secure token

lib/Uphold/Exception/ConnectException.php, lib/Uphold/HttpClient/Handler/ErrorHandler.php, test/Uphold/Tests/Unit/HttpClient/Handler/ErrorHandlerTest.php
This PR adds error handling of guzzle connect exceptions. For instance, when the host could not be resolved.
=> Add error handling for connect exceptions

lib/Uphold/Paginator/Paginator.php
Assigning the default paginator limit on the constructor arguments was allowing the paginator limit to be `null`.
=> Fix paginator default limit

lib/Uphold/HttpClient/Handler/ErrorHandler.php, test/Uphold/Tests/Unit/HttpClient/Handler/ErrorHandlerTest.php
This adds handling for empty responses on a `RequestException` by throwing a `RuntimeException` with the `RequestException` message and code.
=> Add empty responses handling

README.md
This fixes another occurrence of the API documentation url on the `README.md` file.
=> Fix API documentation url

lib/Uphold/Exception/UpholdClientException.php, lib/Uphold/Paginator/Paginator.php, test/Uphold/Tests/Unit/Paginator/PaginatorTest.php
This PR adds missing unit tests to the `Paginator` class. Also, it fixes the name of the `UpholdClientExtension` when handling pager errors.
=> Improve Paginator tests

lib/Uphold/HttpClient/Message/Response.php, test/Uphold/Tests/Unit/HttpClient/Message/ResponseTest.php
This fixes the handling of response errors when `errors` is a multidimensional array.
=> Fix handling of response errors

lib/Uphold/HttpClient/HttpClient.php, lib/Uphold/HttpClient/HttpClientInterface.php, test/Uphold/Tests/Unit/HttpClient/HttpClientTest.php
This PR improves `HttpClient` by removing unused method `setHeaders` and improving unit tests.
=> Improve HttpClient

test/Uphold/Tests/Unit/UpholdClientTest.php
This improves `UpholdClient` unit tests by adding one missing test.
=> Improve UpholdClient unit tests

examples/Transaction.php, lib/Uphold/Model/Card.php, test/Uphold/Tests/Unit/Model/CardTest.php
This adds message option to the `Card.createTransaction` method allowing to create a new transaction with a custom message.
=> Add message option to Card.createTransaction

examples/Transaction.php, lib/Uphold/Model/Card.php, test/Uphold/Tests/Unit/Model/CardTest.php
This adds the functionality to create and commit a transaction in a single request.
=> Add commit option to createTransaction

examples/Card.php, lib/Uphold/Model/Card.php, lib/Uphold/Model/CardInterface.php, test/Uphold/Tests/Unit/Model/CardTest.php
Uphold API has introduced a (breaking change)[https://uphold.com/en/developer/blog/posts/api-changes/breaking-change-regarding-crypto-addresses-on-uphold-cards] by not adding automatically a crypto address to a new card. This now must be done manually. 
This PR adds `createCryptoAddress` method to Card model and updates it's tests and examples. It also adds `addAddress` private method so that we can add a new address to the addresses list.
=> Add create crypto address to card model

examples/Account.php, examples/Card.php, examples/Reserve.php, examples/Ticker.php, examples/Transaction.php, examples/User.php, lib/Uphold/Command/CreateTokenCommand.php, lib/Uphold/UpholdClient.php, test/Uphold/Tests/Functional/ReserveTest.php, test/Uphold/Tests/Functional/TestCase.php
This PR adds sandbox option allowing to choose which API url will be used on the client requests. It is also possible to provide `base_url` option to override this behaviour.
The sandbox option was added to CreateTokenCommand allowing to create a token in Uphold Sandbox.
This also adds sandbox option as true to the functional tests using the Sandbox API instead of the production one.
All examples were updated with the sandbox option which makes the developers aware of the sandbox option, although it's not mandatory.
Closes #84.
=> Add Sandbox option

lib/Uphold/Model/User.php, test/Uphold/Tests/Unit/Model/UserTest.php
This fixes user revoke token method that needs to call client delete method.
=> Fix user revoke token method

lib/Uphold/Model/Card.php, lib/Uphold/Model/CardInterface.php, test/Uphold/Tests/Unit/Model/CardTest.php
This PR updates the `card.getAddresses` method by removing the `$addresses` property from the model which no longer is provided on the `/me/cards/:cardId`.
Now, when the user calls the `card.getAddresses` method a request is made to the Uphold's API which retrieves the card's list of addresses.
=> Update card.getAddresses method to retrieve from API

.travis.yml, travis.php.ini
This PR adds a php configuration file for travis which increases the php memory limit. This is for machines other than hhvm.
=> Add php configuration file for travis

.travis.yml
Travis CI issue a statement in which they encourage to cycle any security credentials that may have been in use as encrypted environment variables on Travis CI.
=> Update code climate encrypted repo token

lib/Uphold/UpholdClient.php, test/Uphold/Tests/Unit/UpholdClientTest.php
This fixes the handling of the user authorize response by retrieving the access token from the array that is given by the `/oauth2/token` endpoint.
=> Fix handling of user authorize response

.travis.yml, travis.sh
This updates the travis scripts to disable `xdebug` at `composer update`. Running `composer` commands while `xdebug` is loaded [reduces speed considerably](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer) and it was causing some builds to fail at `Travis`.
`xdebug` is being disabled at before script and enabled at scripts because it's necessary to generate the code coverage report.
=> Update travis scripts to disable xdebug in composer

lib/Uphold/Command/CreateTokenCommand.php
This renames the `getDescription` method on the create token command to `getPATDescription` since the `getDescription` method is used by the console to write the command description helper.
=> Fix create token description method name
